<a href="javascript:;" id="homepage-gallery-watch" class="block gallery-item gallery-item-watch gallery-item-dark" data-ac-gallery-item aria-label="Apple Watch Series 2. Introducing Series 2.">
      <div class="gallery-item-content">
        <div class="gallery-item-lockup-wrapper">
          <h1 class="homepage-headline" aria-hidden="true">[field:title/]</h1>
          <p class="intro"> [field:ms/] </p>
        </div>
      </div>
      <figure class="gallery-image gallery-image-watch-alt" style="background-image: url([field:litpic/]);"></figure>
      <picture>
        <source srcset="[field:picname/]" media="(max-width: 48em)">
        <img class="img-responsive" srcset="/skin/images/null.png"> </picture>
      </a>