<li class="col-xs-6 col-sm-4 col-md-4 col-lg-4"> <a href="[field:arcurl/]">
          <div class="case_img hover-shadow"> <img src="/skin/images/loading.gif" data-original="[field:picname/]" class="img-responsive lazy"/>
            <div class="case_cover"></div>
          </div>
          </a>
          <div class="case_txt">
            <div class="case-left case_name">[field:title/]</div>
            <div class="case-right category">类别：[field:typename/]</div>
            <div class="clearfix"></div>
          </div>
        </li>