<a href="javascript:;" id="homepage-gallery-madeincny" class="block gallery-item gallery-item-static gallery-item-madeincny gallery-item-dark" data-ac-gallery-item aria-label="Made in CNY">
      <div class="gallery-item-content">
        <div class="gallery-item-lockup-wrapper">
          <h1 class="homepage-headline" aria-hidden="true">[field:title/]</h1>
          <p class="intro"> [field:description function="cn_substr(@me,400)"/] </p>
        </div>
      </div>
      <figure class="gallery-image gallery-image-madeincny" style="background-image: url([field:picname/]);"></figure>
      <picture>
        <source srcset="[field:picname/]" media="(max-width: 48em)">
        <img class="img-responsive" srcset="/skin/images/null.png"> </picture>
      </a>