<?php
$z[0]=Array("field","",41,70);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n      <div class=\"index-news-one\"><a class=\"inews-one-l\" href=\"[field:arcurl/]\">[field:title/]</a> <span class=\"inews-one-r\">[[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]]</span> </div>\r\n      ",83,350);
$z[1][4]=array();
$z[1][4]['row']="3";
$z[1][4]['titlelen']="50";
$z[1][4]['orderby']="pubdate";

?>