<?php
$z[0]=Array("channelartlist","\r\n        <li>\r\n          <dl>\r\n            <dt> <a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a> <i class=\"f-arrow\"><img src=\"/skin/images/f-arrow.png\"></i> </dt>\r\n            <div class=\"footer-sub-menu\"> {dede:channel type='son' noself='yes'}\r\n              <dd><a href=\"[field:typeurl/]\">[field:typename/]</a></dd>\r\n              {/dede:channel} </div>\r\n          </dl>\r\n        </li>\r\n        ",128,614);
$z[0][4]=array();
$z[0][4]['typeid']="top";
$z[0][4]['row']="6";
$z[1]=Array("global","",1152,1173);
$z[1][4]=array();
$z[1][4]['name']="cfg_qq";
$z[2]=Array("global","",1352,1374);
$z[2][4]=array();
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",1425,1449);
$z[3][4]=array();
$z[3][4]['name']="cfg_phone";
$z[4]=Array("global","",1501,1525);
$z[4][4]=array();
$z[4][4]['name']="cfg_email";
$z[5]=Array("global","",1568,1590);
$z[5][4]=array();
$z[5][4]['name']="cfg_add";
$z[6]=Array("flink","\r\n          <li> [field:link/] </li>\r\n          ",1781,1889);
$z[6][4]=array();
$z[6][4]['titlelen']="20";
$z[6][4]['row']="20";
$z[6][4]['type']="text";
$z[7]=Array("global","",1951,1977);
$z[7][4]=array();
$z[7][4]['name']="cfg_powerby";
$z[8]=Array("global","",2093,2117);
$z[8][4]=array();
$z[8][4]['name']="cfg_beian";

?>