<?php
$z[0]=Array("channel"," <a href=\"[field:typeurl/]\">[field:typename/]<i></i></a> ",205,378);
$z[0][4]=array();
$z[0][4]['type']="top";
$z[0][4]['currentstyle']="<a href='~typelink~' class='thisclass'>~typename~<i></i></a>";
$z[1]=Array("global","",556,582);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("channel"," <a href=\"[field:typeurl/]\">[field:typename/]<i></i></a> ",732,905);
$z[2][4]=array();
$z[2][4]['type']="top";
$z[2][4]['currentstyle']="<a href='~typelink~' class='thisclass'>~typename~<i></i></a>";
$z[3]=Array("include","",1089,1127);
$z[3][4]=array();
$z[3][4]['filename']="wapfoot.htm";
$z[4]=Array("channel"," <a href=\"[field:typeurl/]\">[field:typename/]<i></i></a> ",1400,1573);
$z[4][4]=array();
$z[4][4]['type']="top";
$z[4][4]['currentstyle']="<a href='~typelink~' class='thisclass'>~typename~<i></i></a>";
$z[5]=Array("global","",1881,1903);
$z[5][4]=array();
$z[5][4]['name']="cfg_tel";
$z[6]=Array("global","",2207,2228);
$z[6][4]=array();
$z[6][4]['name']="cfg_qq";
$z[7]=Array("global","",2348,2370);
$z[7][4]=array();
$z[7][4]['name']="cfg_qqq";
$z[8]=Array("global","",2559,2582);
$z[8][4]=array();
$z[8][4]['name']="cfg_qqqq";

?>