<?php
$z[0]=Array("field","",333,352);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",353,379);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",420,449);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",489,547);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",970,1005);
$z[4][4]=array();
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n        <li>\r\n          <div><a href=\"[field:typeurl/]\">[field:typename/]</a></div>\r\n          <i></i> </li>\r\n        ",1735,2029);
$z[5][4]=array();
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<li class='cur'> <div><a href='~typelink~'>~typename~</a></div> <i></i></li>";
$z[6]=Array("list","\r\n        <li class=\"col-xs-6 col-sm-4 col-md-4 col-lg-4\"> <a href=\"[field:arcurl/]\">\r\n          <div class=\"case_img hover-shadow\"> <img src=\"/skin/images/loading.gif\" data-original=\"[field:picname/]\" class=\"img-responsive lazy\"/>\r\n            <div class=\"case_cover\"></div>\r\n          </div>\r\n          </a>\r\n          <div class=\"case_txt\">\r\n            <div class=\"case-left case_name\">[field:title/]</div>\r\n            <div class=\"case-right category\">类别：[field:typename/]</div>\r\n            <div class=\"clearfix\"></div>\r\n          </div>\r\n        </li>\r\n        ",2193,2804);
$z[6][4]=array();
$z[6][4]['pagesize']="9";
$z[7]=Array("pagelist","",2873,2939);
$z[7][4]=array();
$z[7][4]['listitem']="index,end,pre,next,pageno";
$z[7][4]['listsize']="2";
$z[8]=Array("include","",3025,3060);
$z[8][4]=array();
$z[8][4]['filename']="form.htm";
$z[9]=Array("include","",3148,3185);
$z[9][4]=array();
$z[9][4]['filename']="footer.htm";

?>